name: on commit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  page_build:
  release:
    types:
      - created

jobs:
  update_notion:
    runs-on: ubuntu-latest
    name: Fetch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
